### ISSUE TITLE
Using the SQLAlchemy 2 native UUID as the column type breaks cursor pagination

### ISSUE THREAD

**Issue by thomaserlang** [djrobstep/sqlakeyset#104]
Using the sa.UUID as the column type breaks the pagination:

```
sqlalchemy.exc.StatementError: (builtins.AttributeError) 'str' object has no attribute 'hex'
```

The issue happens in the `pair_for_comparison` function when it applies the preprocessing: 
```
value = compval.type.bind_processor(dialect)(value)
```
resulting in the UUID being converted into a str prematurely.  
It must pass the uuid.UUID value directly when using the sa.UUID as the column type.

Commenting out the line `value = compval.type.bind_processor(dialect)(value)` resolves the issue.

**Comment by thomaserlang** [comment]
Yes, the issue is that sqlakeyset correctly parses the cursor value into a UUID but then converts it back into a str before executing the query.

Example:

sqlalchemy  2.0.27
sqlakeyset 2.0.1708730727

```python
import asyncio
import sqlalchemy as sa
from sqlalchemy.orm import Mapped, mapped_column, DeclarativeBase
from sqlalchemy.ext.asyncio import create_async_engine
from sqlakeyset.asyncio import select_page
from uuid import UUID, uuid4

class Base(DeclarativeBase):
    pass

class User(Base):
    __tablename__ = 'users'

    id: Mapped[UUID] = mapped_column(primary_key=True)
    name: Mapped[str]


async def test():
    engine = create_async_engine('sqlite+aiosqlite:///', echo=True)

    async with engine.connect() as conn:
        await conn.run_sync(Base.metadata.create_all)
        await conn.execute(
            sa.insert(User).values([
                {'id': uuid4(), 'name': 'Test1'},
                {'id': uuid4(), 'name': 'Test2'},
            ])
        )
        query = sa.select(User.id).order_by(User.id)
        await conn.execute(query)
        
        page = await select_page(conn, query, per_page=1)
        assert page.paging.next != None
        page2 = await select_page(conn, query, per_page=1, page=page.paging.next)
        assert page2.paging.next == None

    await engine.dispose()

asyncio.run(test())
```

**Comment by acarapetis** [comment]
Thanks for the example. Looks like it's failing only with sqlite, not with postgresql; so it's something to do with the fact that `Uuid` falls back to using strings for some database backends - in sqlalchemy this must be handled somewhere at a higher level than `bind_processor`. I'll look into it.

**Comment by thomaserlang** [comment]
I used sqlite just for this example purpose. I ran into the issue first using MariaDB.

**Comment by acarapetis** [comment]
Looks like sqlalchemy only implements native UUID for postgresql so that makes sense.

**Comment by acarapetis** [comment]
So apparently sqlakeyset has been unknowingly working around https://github.com/sqlalchemy/sqlalchemy/issues/8992 for a long time - our call to `bind_processor` *should* be unnecessary, but since we're sometimes using the value inside a `tuple_` it's required due to that bug. The problem is the *sometimes* - in the case where there's only a single ordering column, we're not using tuples, and thus processing (the `.hex` in this case) is applied twice - once by us, once by sqlalchemy.

Quick fix for now is to only apply `bind_processor` in the case where we're using `tuple_` - I'll publish this soon.

Definitely going to run into issues if that bug is fixed, though - will try to think of a way to future-proof it. Worst case I just put a version check after the fact.
