### ISSUE TITLE
Accessing page at certain index

### ISSUE THREAD

**Issue by nikoladsp** [djrobstep/sqlakeyset#13]
Hi,
I am experimenting with sqlakeyset library and have one question: if I want to access some specific page; say page number 10 (out of total 11 pages) - do I have to 'unpack' each page while looping like this:
```python
for i in range(1, page_index):
    if not page.paging.next:
        break

    page = get_page(query, per_page=per_page, page=page.paging.next)
```
I tried without unpacking, but that does not work. I am not sure  will this perform good on large datasets.

Thank you kindly.

Bst regards

**Comment by nikoladsp** [comment]
Hi,
thank you for the response! Number of records will be *really* big, son not sure offset-based is an option.

As for another 2 suggestions - I as also thinking about to keep 'current' page in Flask session perhaps and use it as UI navigates forward/backward.Predetermining the offset - thi I have to do with 'classic' offset-based paging or *sqlakeyset*?

Thank you very much!

**Comment by ocavue** [comment]
Our product has a lot of records too, so we have to use keyset instead of offset. And we want people to choose their pages instead of only two next/previous buttons. The key to our solution is that we only allow "small jump".

Just using google's UI as an example. Google won't let a user go to page 965 directly. What user can do is go to page 10 from page 1 or go back to page 5 from page 10. 

![image](https://user-images.githubusercontent.com/24715727/50650719-3b9e2900-0fbc-11e9-9cd0-b59cb0f270eb.png)


If the user chose next or previous page, then is just normal keyset. If the user chose to jump over some pages, we search `page_nums * per_page` items from the database and only return the last (or the first) `per_page` items to the frontend. Since we limit the size of `page_nums`, the performance is acceptable.

Holp this will help. @nikoladsp

**Comment by nikoladsp** [comment]
Thanks, I understand the idea. Atm, since I am in a hurry - so I left offset+limit, but as soon as pressure drops a bit I am going to try this solution!

Best regards
