### ISSUE TITLE
Is it possible to use this library when querying multiple tables

### ISSUE THREAD

**Issue by acnebs** [djrobstep/sqlakeyset#19]
I have a complex query with that is getting rows from a table and counts related to those rows from various tables, e.g.

```
s.query(
            CM1,
            sq_cc.c.child_count,
            func.count(Comment.id.distinct()).label("comment_count"),
            func.count(CM2.id.distinct()).label("member_count"),
            func.count(CM2.id.distinct()).filter(CM2.liked).label("likes"),
            Card.comments.any(Comment.user_id == CM1.user_id),
)
```

Is it possible to use this library with such a query? My initial attempts were met with a `TypeError: Boolean value of this clause is not defined` error, and when I tried the change in #7 I got a `sqlalchemy.orm.exc.UnmappedColumnError: No column cards.created_when is configured on mapper mapped class CardMembership->card_memberships...` error.

Any thoughts? I'm thinking I should just implement the paging manually for this query.

**Comment by djrobstep** [comment]
So the query works fine without the paging?

I'm not sure how to go about fixing the ORM errors - since writing this library I haven't worked with SQLAlechemy ORM code much and so my memory of the specifics is rusty. This is the kind of territory where I find ORMs get frustrating and cost more time troubleshooting than they save.

If you decide to go down the manual path I did implement similar functionality for vanilla SQL queries in [`results`](https://github.com/australianunions/results). Unfortunately it isn't particularly well documented but the `db.paged(` method here is what you would want: https://github.com/australianunions/results/blob/master/results/connections.py#L99

**Comment by acnebs** [comment]
Yep, the query works.

Gotcha. I was starting to cobble something together from your code (and previous knowledge of the subject) but I'll definitely have a look at results as well. Thanks for the help!

**Comment by acarapetis** [comment]
@acnebs If you have the time, it would be great if you could try your query against the latest master and see if the paging works now.

**Comment by acarapetis** [comment]
If you get around to trying this again and still have issues with an up-to-date version of sqlakeyset, let us know and we'll re-open this issue.
