### ISSUE TITLE
Error with aliased columns (ie with from_self) if model contains field named "info"

### ISSUE THREAD

**Issue by koirikivi** [djrobstep/sqlakeyset#24]
I have an SQLAlchemy orm model with a column named `info`.

Normally, `get_page` works just fine for queries generated using that model. However, if I construct using the `from_self` construct, e.g. `session.query(MyModel).from_self().order_by(MyModel.some_field)`, calling `get_page` on it raises an exception:

```
  File "/xxx/python3.8/site-packages/sqlakeyset/columns.py", line 328, in derive_order_key
    mapper = expr.parent
AttributeError: type object 'MyModel' has no attribute 'parent'
```

The reason is that this piece of code incorrectly assumes that `expr` is an attribute based on just the fact it has an attribute named `info`: https://github.com/djrobstep/sqlakeyset/blob/6bcc01e/sqlakeyset/columns.py#L327

I think by bare minimum that code should check `hasattr` for both `info` and `parent` (and `name`), and that would not likely break any existing code.
That said, there's probably a better way to do that check. After all, it's not unreasonable for a model to have fields `info`, `parent` and `name`.

The reason that this only occurs for the query with `from_self` is that the check on this line: https://github.com/djrobstep/sqlakeyset/blob/6bcc01e/sqlakeyset/columns.py#L321
fails with an error (which is swallowed by the `try-except` clause) like this:
```
sqlalchemy.orm.exc.UnmappedColumnError: No column %(140242126363088 anon)s.my_model_some_field is configured on mapper mapped class MyModel->my_model...
```

For the query without `from_self`, the mapper finds the column correctly and thus the function returns before it has a change to crash on line 328.

**Comment by acarapetis** [comment]
Thanks for your report! The current introspection in `derive_order_key` is indeed pretty ad-hoc - since sqlalchemy's internals have a reasonably strong type heirarchy, a lot of those `hasattr` checks can probably be replaced by `isinstance` checks.

I'll try to find some time to fix this soon, but we're also very happy to accept pull requests: if you wanted to add a minimal test in [test_paging.py](https://github.com/djrobstep/sqlakeyset/blob/master/tests/test_paging.py) that fails due to this bug, that would be a great starting point.

**Comment by koirikivi** [comment]
Hey @acarapetis, thanks so much for tackling this and sorry for not having the time to contribute the test myself. Waiting eagerly for this to get merged :)
