### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by kasium** [djrobstep/sqlakeyset#70]
Hi guys,
thanks a lot for creating this library. Since SQLAlchemy has type hints (in typeshed and as sqlalchemy2-stubs), it would be great if types could also be added to this library.

Do you think this is possible?

**Comment by acarapetis** [comment]
Hey there, thanks for the suggestion. It's a good idea for sure. I did start work on this a little while ago (https://github.com/djrobstep/sqlakeyset/compare/master...acarapetis:sqlakeyset:typing), but realized that it's probably a wasted effort at this point, since they won't really become useful until we fully support sqlalchemy2, which is going to require somewhat of a rewrite. Whenever I find time to tackle #54 (or someone else submits a PR for it), rest assured that type hints will be a high priority :)

**Comment by kasium** [comment]
Thanks a lot!
